# Generated by Django 2.2.5 on 2019-09-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190920_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images1',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
