# Generated by Django 2.2.5 on 2019-09-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_images1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images1',
        ),
    ]
