# Generated by Django 2.2.5 on 2019-09-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_images1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images1',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
